### ISSUE TITLE
Can to get maxFlightHeight through KeyManager

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#233]
## Description

After aircraft is ready, I found that if I get maxFlightHeight through code below, I can only get `nil` value, no matter how many times I tryed:

```Swift
let key = DJIFlightControllerKey(param: DJIFlightControllerParamMaxFlightHeight)!
let keyManager = DJISDKManager.keyManager()!
let value = keyManager.getValueFor(key)
```
by if I get the value with async calling, I can get the right value:

```
let key = DJIFlightControllerKey(param: DJIFlightControllerParamMaxFlightHeight)!
let keyManager = DJISDKManager.keyManager()!
keyManager.getValueFor(key, withCompletion: { (value, error) in
    // The value is valid
})
```

And after I called the code above, I can also get the valid value through sync call:

```Swift
keyManager.getValueFor(key, withCompletion: { (value, error) in
    // The value is valid
    let syncValue = keyManager.getValueFor(key) // The syncValue is also valid now
})
```

or

```Swift
helper.fetchFlightController.getMaxFlightHeight(completion: { (height, error) in
    let syncValue = keyManager.getValueFor(key) // The syncValue is also valid now  
})
```

## Environment

* iOS Device: iPhone X
* iOS Version: iOS 11.3 beta
* DJI Device: Phantom 4 Pro
* Aircraft Firmware: 01.00.0128
* RC Firmware: 02.01.01.00

**Comment by aksh1t** [comment]
This is expected behavior. The first time you call the synchronous getter, the SDK does not have a cached value for the key that you are requesting and so it does not return anything (since querying the drone is an async operation). The async getter on the other hand will try looking for a cached value first, and if it does not find any cached value it will query the drone (will also store the value in cache) and give you the result. After the cache has a value for the key, you can call the synchronous getter and use the cached value if you need.
