### ISSUE TITLE
LDM Manager does not allow enable until connected to aircraft, allowing long term connections to SDK servers

### ISSUE THREAD

**Issue by dokazaki** [dji-sdk/Mobile-SDK-iOS#243]
It appears to be impossible to stop network traffic to DJI servers prior to connecting the iPad to the Aircraft and the Aircraft appears to also be required to have GPS lock. This is unacceptable in applications that have major functionality prior to flying the DJI aircraft and defeats the purpose of the LDM Manager.

Per stack overflow (DJILDMManagerSupportedChangedNotification), the app cannot call enableLDM until the DJILDMManagerSupportedChangedNotification is sent out. However, this notification is never sent until the iPad is connected to the RC which is sync'd to the aircraft. Also it appears to require GPS lock - when using the DJI simulator, the LDM allowed notification only gets set out after the simulator is initialized and the aircraft gets GPS lock.

* This is an LDM Manager defect - the app should be able to enable it BEFORE the product is connected, after which LDM Manager should wait for product connection. If on connection the locale is determined to be in China or another country prohibiting LDM, the Manager should then disable LDM.

For example, prior to connecting to the aircraft, the following connection tunnels were observed:
- https://active.dji.com/ - CONNECT keeps getting sent and sets up connections that last until they drop. Observed one connection that went as long as 3045ms. Thousands of connections are observed over a short period of time.
- https:/mydjiflight.dji.com - lot of short tunnel connections that get set up and dropped, set up and dropped over and over. Hundreds of connections are observed over a short period of time.

Why does the SDK need these tunnels when there is no connected product? What gets sent over these tunnels? These connections consume bandwidth that the app needs for functions prior to connecting to and flying the aircraft.

Execution environment:
- DJI Phantom 4 Pro - running Assistant 2 simulator
- iPad Pro 10.5"
- iOS 11.2.6
- DJI iOS Mobile SDK 4.5
- Xcode 9.2

**Comment by XietongLU** [comment]
@dokazaki the flag of isLDMSupported is cached in the hard disk. It means if it is YES in the previous life cycle, it is also YES next time when DJILDMManager starts. The notification is sent only when the value is changed after the initialization so you should not wait for it. 
The correct usage is, after SDKManager is registered for the first time after installation, you should can enableLDM for each life cycle before calling other interfaces of SDK (including registerApp). 
If LDM is enabled successfully, you should see only the connection to dev.dji.com, which is the request used for registration. 
Let me know if you found different behaviour from what I describe. Thanks.

**Comment by shoerob** [comment]
@dokazaki This must be exactly what I've been seeing in https://github.com/dji-sdk/Mobile-SDK-iOS/issues/242. I am writing and testing code from within a building where I am unable to obtain GPS lock. Whether I have a drone connected or not, I get an error. The error I am getting is incorrect, but must be related to not having a GPS lock.

That being said, @XietongLU , enabling LDM for the FIRST time becomes problematic. In order to enable LDM for the first time in an app the following things must happen:

1. DJI SDK must be registered, in order to connect to, and read telemetry from a drone.
2. GPS lock must be obtained.
3. LDM mode can now be enabled.

isLDMSupported cannot be cached until these steps have been completed at least once. Then, if isLDMSupported gets reset later on, these steps must be performed again.

By the time step 1 of this scenario is executed, the SDK is already leaking information deemed sensitive, or private by the consumer of the SDK. Therefor, I am in agreement with @dokazaki that this is a defect in the LDMManager implementation. The correct functionality should be:

- Developers should be able to enable LDM _BEFORE_ the DJI SDK has been registered. A connected drone should not be a requirement of this process.

**Comment by dokazaki** [comment]
@XietongLU - I verified that after a successful LDM enablement, then subsequent app start can call the LDM enable immediately at app startup and it works.

However, the main problem still exists that for new app installation, even after successful DJI SDK app registration, where DJISDKDelegateProxy.appRegisteredWithError() executes with no error, attempts to enable LDM do not work.

**DJISDKManager.ldmManager().isLDMSupported only returns false until an aircraft is connected and the GPS lock is acquired.**

Meanwhile the SDK is tunnelling CONNECT to api.dji-services.com, mydjiflight.dji.com, app-service.skypixel.com, www.skypixel.com

It is this behavior that is unacceptable. Our app needs to be able to register the DJI SDK well before physical aircraft connection so that the user can connect an RC & aircraft at any time and fly. They need to be able to do so without having this unnecessary, extraneous, and what can be construed as suspicious, network traffic occurring.

Please provide some insight into how DJI will address this problem.

**Comment by dokazaki** [comment]
@athiercelin Would you be able to provide some clarification on when this LDM defect will be resolved? Thanks!

**Comment by XietongLU** [comment]
@dokazaki LDM is not supported in China. To determine this (locally), GPS location from the aircraft is required. 
The behaviour of LDM will be improved in the following release. I think you will have better experience after that.

**Comment by dokazaki** [comment]
@XietongLU Thanks for the update, do you know when the next release is scheduled? I have a bit of a deadline to get this resolved in...

**Comment by XietongLU** [comment]
@dokazaki we are trying to make it happen this week but it is not settled yet.

**Comment by dokazaki** [comment]
@XietongLU that's would be great! thanks!

**Comment by dokazaki** [comment]
Looks like 4.5.1 fixed this issue. Opened a new issue (#249) to cover the remaining bugs. Closing this issue as fixed.
