### ISSUE TITLE
Photos not captured when initiated by Remote using DJISDK 4.10 on Mavic 2 Enterprise

### ISSUE THREAD

**Issue by dshackelford** [dji-sdk/Mobile-SDK-iOS#323]
Initiating a photo capture or recording video, via the remote, is not successful while our app is being run. Pressing the buttons on the remote causes nothing to happen. However, while in DJI Pilot or DJI GO 4, photos and videos are recorded.

Mavic 2 Pro and Mavic 2 Enterprise do not take photos via the remote, while running our application. However, Phantom 4 Pro V2 and Phantom 4 Advanced are able to. 

Environment:
DJISDK 4.10
DJIWidget 1.5
iOS 12.3.1
Mavic 2 Enterprise Firmware: 01.01.0400
Mavic 2 Enterprise Remote Control Firmware: 01.01.0400
Mavic 2 Pro Firmware: 01.00.0400
MAvic 2 Pro Remote Control Firmware: 01.00.0400
DJI Go 4: 4.3.20

Any information would be greatly appreciated. 
Thanks,
Dylan Shackelford

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/27050'>Zendesk ticket #27050</a>:<br><br>Dear Dylan,

Thank you for contacting DJI.
Please note that we have removed the RC's shutter button, record button default feature since the 4.8.1.
So, if you need to implement them. To listen to the hardware state of RC remoteController:didUpdateHardwareState and customize them when the button triggered.
 ![](https://djisdksupport.zendesk.com/attachments/token/lHjTOuP9xgyPKKmdK1aINVHp0/?name=inline749474078.png)​

Thanks,

Luce Luo
DJI Dev Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/lHjTOuP9xgyPKKmdK1aINVHp0' target='zd_attach'>inline749474078.png</a>
