### ISSUE TITLE
Please add SDK support for Osmo Pocket

### ISSUE THREAD

**Issue by ikthreeo** [dji-sdk/Mobile-SDK-iOS#455]
Guys it has been years and everytime the request is made it gets closed with a "we have forwarded the request to the team". Are there any plans on supporting DJI Osmo Pocket to the SDK? Many users are interested in expanding the abilities, please let us know.

Instead of burdening you with feature requests atleast this will let us add some of those ourselves.

Thank you

Some other posts:
[https://github.com/dji-sdk/Mobile-SDK-iOS/issues/314](https://github.com/dji-sdk/Mobile-SDK-iOS/issues/314)
[https://github.com/dji-sdk/Mobile-SDK-Android/issues/415](https://github.com/dji-sdk/Mobile-SDK-Android/issues/415)

[https://forum.dji.com/forum.php?mod=viewthread&tid=36992](https://forum.dji.com/forum.php?mod=viewthread&tid=36992) (From 2015)
[Too many to add](https://forum.dji.com/forum.php?mod=forumdisplay&filter=typeid&typeid=557&fid=129&srchforum=sdk)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/46588'>Zendesk ticket #46588</a>:<br><br>Dear Client
Thank you for contacting DJI.

SDK has no plan to support Osmo Pocket because we are focusing on other higher prioty prodcut supportability.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by ikthreeo** [comment]
Okay thanks for the response. I will look into Feiyu Pocket or Snoppa Vmate in that case.
