### ISSUE TITLE
M300 RTK with H20T setMode fails

### ISSUE THREAD

**Issue by dylandrones** [dji-sdk/Mobile-SDK-iOS#485]
Hello,

DJISDK 4.15 does not allow for the M300RTK to set the H20T camera mode to Photos.

`[camera setMode:DJICameraModeShootPhoto withCompletion:^(NSError * _Nullable error) {`

returns:

`Error Domain=DJISDKErrorDomain Code=-1013 "Current product does not support this feature.(code:-1013)" UserInfo={NSLocalizedDescription=Current product does not support this feature.(code:-1013)}`

I have to change the mode in DJI Pilot to be able to trigger photos programmatically. 

Any information on this issue would be greatly appreciated. 

Environment:
DJISDK 4.15
AC: 02.04.0102
RC: 02.04.01.03
H20T: 02.04.01.01

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50935'>Zendesk ticket #50935</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
For the M300RTK drone, should use the setFlatMode:withCompletion method instead of the setMode:withCompletion.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
