### ISSUE TITLE
Connect Mavic Air 2 to iPhone via wifi or bluetooth

### ISSUE THREAD

**Issue by tommypham** [dji-sdk/Mobile-SDK-iOS#497]
I ran sample app: ObjC Demo . I can connect the app to aircraft via USB cable, but I can not find a way to connect my iPhone 7 to Mavic Air 2 by wifi or bluetooth.
Can anyone help me on this issue ?
Please see the attachment for more detail about aircraft and the app.
![IMG_3319](https://user-images.githubusercontent.com/734649/139537495-4d47cb0d-b0e4-466a-8244-5a3c7c6ca12d.PNG)
![IMG_3320](https://user-images.githubusercontent.com/734649/139537499-64f64012-1719-4662-ae85-6a67f32438b7.PNG)
![IMG_3321](https://user-images.githubusercontent.com/734649/139537500-0ccc6cca-4443-4c17-af4d-977115f9e7d2.PNG)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/55453'>Zendesk ticket #55453</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/55453'>Zendesk ticket #55453</a>:<br><br>Your app should be connected the to Mavic Air 2 via USB cable. Wifi and Bluetooth could not do that.
<br><p><em><small>°°°</small></em></p>
