### ISSUE TITLE
iOS 9.0 App Transport Security policy 

### ISSUE THREAD

**Issue by mohammedDehairy** [dji-sdk/Mobile-SDK-iOS#5]
i am using an older version of the SDK because using the current version will force major refactoring in the app , but media fetching is not working because of iOS 9.0 new App Transport Security policy , so i were wandering if you can send the list of url's used to fetch media so that i can add them to the App Transport Security policy exclusion list to white list them as a fix for my problem .

i appreciate your help.

**Comment by oliverou** [comment]
Hi, this problem is due to iOS9's App Transport Security Policy, by default, all the network request should use HTTPS, since we use HTTP in the DJI Mobile SDK, so the syncing photos and videos doesn't work. You can try to modify the following property in the info.plist file of your Xcode project as shown below:
![nsallowsarbitraryloads](https://cloud.githubusercontent.com/assets/13310805/10719996/1dbf7406-7bcd-11e5-8962-6a76eadcd639.png)
Try to modify the NSAllowsArbitraryLoads value to YES ​and test it again, it should work.
