### ISSUE TITLE
[Phantom 4] How to get Voltage of Cells?

### ISSUE THREAD

**Issue by lygialiem** [dji-sdk/Mobile-SDK-iOS#504]
Hi DJI Devs team.

First of fall, thank you very much for your wonderful SDK. Currently i'm building app to control DJI Phantom 4. I want to get voltage of cells like image below. In DJIBattery, I found a function: "
getCellVoltagesWithCompletion", but completion always return error with description: "Current product does not support this feature.(code:-1013)".

How can i get voltage of cells. Thank you very much and Best Regard.

https://drive.google.com/file/d/1Qwty-D-EmoOJyQf4Qs_PybaY5rMoc76M/view?usp=sharing

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/60321'>Zendesk ticket #60321</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/60321'>Zendesk ticket #60321</a>:<br><br>I tested this API with P4RTK aircraft and the IOS MSDK 4.15.2 version, and the cell voltages could be obtained.

Could you show us your program part, and what aircraft type you are using( which one in the P4 series )?
<br><p><em><small>°°°</small></em></p>

**Comment by lygialiem** [comment]
Hi Devs.

Thank you for your response. It's all about my code. Thank you for your support.

Best Regard
