### ISSUE TITLE
SDK 4.16 Xcode 13.3 FFmpeg upload to Apple Store Info.plist

### ISSUE THREAD

**Issue by hdrpano** [dji-sdk/Mobile-SDK-iOS#510]
You have to remove the item CFBundleSupportedPlatdorms iPhoneSimulator from the FFmeg.framework (DJIWidget 1.6.6) for Apple Store uploads. The actual Info.plist file doesn't work. 

After you have installed DJIWidget with pod install you have to edit the Info.plist file. 
I removed all simulator entries.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/62476'>Zendesk ticket #62476</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by brien-crean** [comment]
@hdrpano Thank you I've been stuck on this issue. Just to clarify for others you have to open the generated Info.plist inside the FFMpeg framework with Xcode or you cannot edit it. I first tried with a text editor assuming it was an XML file like other plist files

Inside Frameworks folder - Right click FFMpeg - show in finder - open Info.plist with Xcode
