### ISSUE TITLE
CustomMission with WaypointMission take a long time to takeoff (Start Mission)

### ISSUE THREAD

**Issue by guicolares** [dji-sdk/Mobile-SDK-iOS#57]
Hi, 

I'm creating a custom mission with 10 or more waypoints and one waypoint mission step. 

When is uploading the mission (prepare mission function called) is really fast but then start is taking 10 or more seconds to execute the takeoff.

There is no action for each waypoint and no erros.

I have no clue what to do to fix this.
SDK version: 3.4

Is there way to change the limit of waypoints in WaypointMission ? 

Thanks.

**Comment by oliverou** [comment]
Hi @guicolares, thanks for your feedbacks. It is due to the mechanism of the custom mission. It will not upload the waypoint mission step inside the custom mission during the upload process. It would upload it only when the custom mission "starts". So it would take some time when you start the custom mission, because uploading the waypoint is time-consuming.
