### ISSUE TITLE
FFmpeg is too big and useless

### ISSUE THREAD

**Issue by wxlpp** [dji-sdk/Mobile-SDK-iOS#61]
we are development on iOS8.0+,FFmpeg is too big and useless.Can you provide a lean version which is Remove FFmpeg.

**Comment by XietongLU** [comment]
What do you mean "FFmpeg is useless"? 
FFmpeg is required by VideoPreviewer, which is the component is used to decode video feed from DJI Product. If you don't need to show the live view from our product (say, you are using Osmo Mobile), you can remove the whole VideoPreviewer reference from your project.

**Comment by d0n13** [comment]
It works ok but its not as clear as the GO app. Are there setting we can tweak to make it brighter with a bit more pop.  Also I see reference to what may be zebra settings for over exposure on screen. Can we enable this easily?

How easy would it be to stream this to YouTube from this ffmpeg mod? Would you guys consider adding this at some stage? It would be awesome if you could. I really need to add that to my app and I have no idea where to start with it as I have no experience in that area. And the code looks alien to me as it's mostly C and horrendously technical.

**Comment by XietongLU** [comment]
You can add shader into VideoPreviewer to tweak the video feed. The zebra effect is still in experiment stage. 
The stream this to Youtube, you may need other libraries to do so. We will not consider adding this shortly because most of those libraries have complex licenses. 
I understand the difficulty of development related to video encoding, decoding, etc, but there are higher priority tasks and we don't have other resource to work on the live streaming stuff.
