### ISSUE TITLE
Please provide RTMP video streaming example for DJI SDK

### ISSUE THREAD

**Issue by EonKid** [dji-sdk/Mobile-SDK-iOS#77]
I am building  iPad application in which i have to  live stream video  of DJI Phantom drone .I wanted to stream video from iPad.Please provide example code live steaming using RTMP similar to what you have you did for your DJI Go iOS app.

-  Please provide RTMP video streaming example for DJI SDK.
-  Crash logs (If you can find it, it would be very helpful)
-  DJI iOS SDK 3.5.1
-  DJI Product - DJI Phantom 3 Advance
-  iOS system version - iOS 9.3.5
-  iOS device type - iPad
-  Xcode version - 8.2.1 

@oliverou @XietongLU @dji-dev

**Comment by EonKid** [comment]
@oliverou  @XietongLU  @dji-dev Can you tell me which sdk you have used to send RTMP packet when we get videobuffer in DJI sdk camera delegate

**Comment by oliverou** [comment]
Hi @EonKid, we don't provide such RTMP video streaming sample for DJI SDK, please modify the VideoPreviewer: <https://github.com/dji-sdk/Mobile-SDK-iOS/tree/master/Sample%20Code/VideoPreviewer> and implement the feature you want. Thanks!

**Comment by EonKid** [comment]
@oliverou  Can you tell me one concept. If i have to send video buffer which i am receiving it in camera delegate to RTMP.Should i have to need to decode it or i can send it directly by converting it to RTMP packet?

**Comment by oliverou** [comment]
Hi @EonKid, if you want to do RTMP live streaming, you need to implement the following steps by yourself:
 
1. Use FFmpeg to parse the video buffer received from the camera of the aircraft and generate a H.264 video stream (For most DJI Products, there is no i frame in the stream).
2. If you want to display the video stream, you can insert a black i frame at the beginning of the video stream and use the VideoPreviewer to do video stream hardware decoding.
3. If you don’t want to display the video stream, you can use the YUV data output from the VideoPreviewer.
4. Since RTMP protocol need different video stream(Need to insert non-black i frame every several seconds).
5. To generate such i frame, you need to use an encoder to convert the YUV data output into i frame and replace the existing frame in the video stream with the generated i frame(Insert i frame).

**Comment by EonKid** [comment]
@oliverou Thanks for your help.

**Comment by EonKid** [comment]
@oliverou @XietongLU @dji-dev  Can you tell me which library you are using to send RTMP packet to server like DJI Go app or you have made some custom library?

**Comment by EonKid** [comment]
@oliverou @XietongLU @dji-dev  Can I get TS frame from camera delegate video buffer?

**Comment by zhouyangwen** [comment]
**@oliverou** I had establish RTMP live streaming between mobile and pc by reencode yuv to h264, but it has serious delay . is there any way to insert iframe into h264 stream without reencode it.

**Comment by AdamKraif** [comment]
Any examples?

**Comment by alzin** [comment]
We entered 2020 and this seems not to be figured out yet, If someone solved it before please share your code with us!!

**Comment by vince-zheng** [comment]
@AdamKraif https://github.com/dji-sdk/Mobile-SDK-iOS
This is an example to use RTMP.
https://github.com/dji-sdk/Mobile-SDK-iOS/tree/master/Sample%20Code/ObjcSampleCode/DJISdkDemo/Demo/Liveview

**Comment by sgallo0692** [comment]
@vince-zheng any tips/advice to use that obj c sample in a swift project? seems pretty painful to pull in given all of the dependancies
