### ISSUE TITLE
fetchMediaListWithResultBlock failed with error

### ISSUE THREAD

**Issue by YunSun** [dji-sdk/Mobile-SDK-iOS#8]
Hello, I am using DJIInspireCamera to get the list of media.
While calling fetchMediaListWithResultBlock: method, I get the following error.
Error:
Error Domain=FetchMediaDomain Code=257 "(null)"
UserInfo={Reason=Abort by App(code:0x101)}}
Can you please let me know what the issue is?

**Comment by caidentity** [comment]
Same here this will be very helpful!

**Comment by dji-dev** [comment]
Hi YunSun, this issue is due to your SD Card mixed with Phantom 3 Series or Inspire 1's media files and Phantom 2 Vision +'s media files, like photos or videos. The camera is currently not compatible with older product's media file. Please make sure your SD Card only contains media files of Phantom 3 Series or Inspire 1's.
