### ISSUE TITLE
Execution of this process has timed out

### ISSUE THREAD

**Issue by inconstructables** [dji-sdk/Mobile-SDK-iOS#95]
I'm working on creating an application to create waypoint missions for the Phantom 4, but when running the app on an iPad, I always get the DJISDKError -1003 with the message "Execution of this process has timed out."
This has happened with both my application and [ScribbleDrone](https://github.com/dbaldwin/ScribbleDrone) when I run it on my iPad.

After switching to an iPad Air 2 and updating firmware, I can now get the app to run in the iOS simulator connected to the real iPad with the Phantom 4 in simulation mode on DJI Assistant 1.0.9.

- DJI iOS SDK Version: 3.5.1
- Phantom 4 (Aircraft: 1.02.0602, Remote Controller: 1.8.0)
- iPad Air 2 with iOS 10.2 (14C92)
- Xcode 8.1 (8B62)

This seems to be the same as [this](https://github.com/DJI-Mobile-SDK-Tutorials/iOS-GSDemo/issues/4), but it has happened with both Swift applications I have tried to run.

**Comment by jgrantr** [comment]
I've seen this issue when I try to run on a real device but my code is making the assumption that I am trying to connect to the bridge app.  This causes really odd things to happen (like the video feed from the drone will work, but running missions won't).  Make sure that when you are trying to run it on the physical device that you are calling:

[DJISDKManager startConnectionToProduct];

and not

[DJISDKManager enableBridgeModeWithBridgeAppIP:@"<some_ip_address>"];

I'm using the following helpful code to enable me to occasionally test on a real device connected to the bridge app.

#if !TARGET_IPHONE_SIMULATOR
	[DJISDKManager startConnectionToProduct];
#else
	#ifdef RELEASE
		#error Release builds should not connect to the drone in debug mode
	#endif
	[DJISDKManager enableBridgeModeWithBridgeAppIP:@"192.168.1.52"];
#endif

Since you are using Swift, you would need to use Swift conditionals, but the same concepts would still apply.

Hope that helps!

**Comment by inconstructables** [comment]
Thanks for the help. I will check that later because both apps have the simulator detection bypassed. I have to download the updated version of Xcode first though, because the iPad was updated.

**Comment by XietongLU** [comment]
Thanks @jgrantr .
